init:
- git clone -q https://github.com/fdorg/flashdevelop.git C:\projects\FlashDevelop
version: 2.7.{build}
platform:
- x86
configuration:
- Release
os: Visual Studio 2015
skip_tags: true
environment:
  PLUGIN_NAME: QuickNavigate
  PLUGIN_PATH: C:\projects\FlashDevelop\External\Plugins\QuickNavigate
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
matrix:
  fast_finish: true
before_build:
- cd ..
- mv %APPVEYOR_BUILD_FOLDER% %PLUGIN_PATH%
- nuget restore %PLUGIN_PATH%\%PLUGIN_NAME%.sln
build:
  project: $(PLUGIN_PATH)\$(PLUGIN_NAME).sln
after_build:
- mkdir %APPVEYOR_BUILD_FOLDER%\$(BaseDir)\Plugins
- mv C:\projects\FlashDevelop\FlashDevelop\Bin\Release\Plugins\%PLUGIN_NAME%.dll %APPVEYOR_BUILD_FOLDER%\$(BaseDir)\Plugins\%PLUGIN_NAME%.dll
- cd %APPVEYOR_BUILD_FOLDER%
- 7z a %PLUGIN_NAME%.zip $(BaseDir)\
- mv %PLUGIN_NAME%.zip %PLUGIN_NAME%.fdz
- set /p var=echo -n "to_md5" | md5sum %PLUGIN_NAME%.fdz
- echo %var%
artifacts:
- path: $(PLUGIN_NAME).fdz
  name: $(PLUGIN_NAME)
  type: zip
deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  description: $(checksum_md5)
  auth_token:
    secure: HK9ej9WVysHQHeTEQ/QTOJmh08xCtDQyDBy5uXWrWV/xROMNkQrTeQv1j2tYOxVw
  artifact: /.*\.fdz/
  on:
    branch: master
